14:15:32 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "127.0.0.1", port 5432 failed: FATAL:  la autentificaci\xf3n password fall\xf3 para el usuario \xabpostgres\xbb\n', 79, 80, 'invalid continuation byte'),)
14:15:32 - ERR - getAll - ("cannot access local variable 'cursor' where it is not associated with a value",)
14:17:44 - ERR - ExecuteNonQuery - (UniqueViolation('llave duplicada viola restricción de unicidad «segu_rol_pkey»\nDETAIL:  Ya existe la llave (rol_id)=(2).\n'),)
15:19:55 - ERR - post - ("Error al validar el request -> {'id_rol': ['Unknown field.']}",)
15:23:22 - ERR - ExecuteNonQuery - (TypeError("object of type 'int' has no len()"),)
15:23:22 - ERR - ExecuteNonQuery - (ForeignKeyViolation('inserción o actualización en la tabla «segu_user_rol» viola la llave foránea «segu_user_rol_id_user_fkey»\nDETAIL:  La llave (id_user)=(17) no está presente en la tabla «segu_user».\n'),)
15:36:29 - ERR - ExecuteNonQuery - (TypeError("object of type 'int' has no len()"),)
15:36:29 - ERR - ExecuteNonQuery - (ForeignKeyViolation('inserción o actualización en la tabla «segu_user_rol» viola la llave foránea «segu_user_rol_id_user_fkey»\nDETAIL:  La llave (id_user)=(18) no está presente en la tabla «segu_user».\n'),)
15:37:38 - ERR - ExecuteNonQuery - (TypeError("object of type 'int' has no len()"),)
15:37:38 - ERR - ExecuteNonQuery - (ForeignKeyViolation('inserción o actualización en la tabla «segu_user_rol» viola la llave foránea «segu_user_rol_id_user_fkey»\nDETAIL:  La llave (id_user)=(17) no está presente en la tabla «segu_user».\n'),)
15:50:20 - ERR - post - ("Error al validar el request -> {'user_password': ['Missing data for required field.']}",)
